version: 2.0
jobs:
  test_configs:
    docker:
      - image: acemod/sqflint
    steps:
      - checkout
      - run: make test_configs
#  linting:
#    docker:
#      - image: acemod/sqflint
#    steps:
#      - checkout
#      - run: sqflint --exit=e -d \@LiveInLifeClient/
#      - run: sqflint --exit=e -d \@LiveInLifeServer/
#      - run: sqflint --exit=e -d LiveInLife.Tanoa/
  build:
    docker:
      - image: liveinlife/armake
    steps:
      - checkout
      - run: make release
workflows:
  version: 2.0
  build:
    jobs:
      - test_configs
#      - linting
      - build

