version: 2
jobs:
  test_configs:
    docker:
      - image: acemod/sqflint
    steps:
      - checkout
      - run: make test_configs
  linting:
    docker:
      - image: acemod/sqflint
    steps:
      - checkout
      - run: sqflint --exit=e -d \@LiveInLifeClient/
      - run: sqflint --exit=e -d \@LiveInLifeServer/
      - run: sqflint --exit=e -d LiveInLife.Tanoa/
  build:
    docker:
      - image: acemod/armake
    steps:
      - checkout
      - run: apt-get install -y -f libssl-dev
      - run: chmod -R 777 tools/
      - run: make release

